services:
- docker

env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=oracle
  - secure: bL9hUeeCwKIRhq5FEt6INEzbPDSqOtP0J+owkPDQUUvux8FmvBBlPTWyobLjzKA+3hy4Om3ABdpoiKevatyOJJ+yx2FZuLU4pko/Tk58G4bTBJLIE9W2JhV2yJcvg1d/Mrzwgq6EYcPrUIXVqE9+lB9Hrduu4P4LemGrY0UDnzsumFcoIaVtQt7kEMLlEq4amNrnnmoZLYGGie3PcUhq26HFYKlWQ6rJihN2Nt2WJX9s7IqkMlCzikYZ4+uYEk6i9uwijF1+tkjWSxkuU1KRd51aQ/rF0xJdyP5eeWl049DPyJT4FI8E+F8r+qjHya7BUpxlouRWTRMyT3e0k3zDQ7htcu4AD3D/kipvZInpOqtTRzBdlCAAYRurqEwbAOA8fPb+eXikdILaf05jGnxTMMp6QPoi7dKjJQKSBWwF3EZDIfWDDYD6g2fEkgfJPB7OW3fd1+F/fms4Kj49XE+qER2OGBAr+HiHQ5QYMTdyzQYTy7r99EcilO3Dk39XT78pvfD3VqLC57qhM944EWEYIvWNi3z3P53tu2YateRzXBPZJAm3hn89SNnjOys3WZy+50BUmvfiayDhboc4t5qA5c4LXiC+NAlM2XN/Ne2rVCRiz+sIfksaxy1FKV5NLXLTI0iV7hEL48rBGiobW95yteQ8sjqFI8bANFowSF9U7h4=

install: true
before_install:
- sudo apt update -y >/dev/null 2>&1 || true
- sudo apt install -y --no-install-recommends curl wget unzip bash >/dev/null 2>&1 || true
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 1521 8080 80

script:
- echo skipped

## we cannot build that image using Travis CI:

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#checkSpace.sh: ERROR - There is not enough space available in the docker container.
#checkSpace.sh: The container needs at least 12 GB, but only 3 GB are available.
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


## but we still doing all these staps locally:

#- export root=$(pwd)
#- wget -q -O docker-images-master.zip https://codeload.github.com/oracle/docker-images/zip/master
#- unzip docker-images-master.zip
#- wget -q -O ${root}/docker-images-master/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/linuxamd64_12102_database_se2_1of2.zip https://github.com/daggerok/oracle/releases/download/oracle/linuxamd64_12102_database_se2_1of2.zip
#- wget -q -O ${root}/docker-images-master/OracleDatabase/SingleInstance/dockerfiles/12.1.0.2/linuxamd64_12102_database_se2_2of2.zip https://github.com/daggerok/oracle/releases/download/oracle/linuxamd64_12102_database_se2_2of2.zip
#- cd ${root}/docker-images-master/OracleDatabase/SingleInstance/dockerfiles/
#- bash ./buildDockerImage.sh -v 12.1.0.2 -s


## tag and push:

#- docker tag oracle/database:12.1.0.2-se2 daggerok/oracle
#- docker tag oracle/database:12.1.0.2-se2 daggerok/oracle:latest
#- docker tag oracle/database:12.1.0.2-se2 daggerok/oracle:12.1.0.2-se
#- docker tag oracle/database:12.1.0.2-se2 daggerok/oracle:12.1.0.2-se2
#- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
#- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}

### TODO: finally test pushed image:

##- docker pull ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
##- >
##  docker run -d --rm --name oracle-se \
##    --shm-size=1g \
##    -p 1521:1521 \
##    -e ORACLE_PWD=$SPRING_DATASOURCE_PASSWORD \
##    ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
##- wait_for 1521
##- docker logs -f oracle-xe &
##- sleep 150
##- cd ${root}/app
##- bash ./mvnw >/dev/null
##- bash ./target/*.jar
##- docker rm -f -v oracle-xe
