= Oracle Database image:https://travis-ci.org/daggerok/oracle.svg?branch=master["Build Status", link="https://travis-ci.org/daggerok/oracle"]
Automation build for docker hub

NOTE: you can build and prepare same image by yourselves. link:https://github.com/oracle/docker-images/tree/master/OracleDatabase/SingleInstance[see details]

.usage (docker)
[sources,bash]
----
docker run -d --rm --name oracle-xe \
  --shm-size=1g \
  -p 1521:1521 \
  -e ORACLE_PWD=password \
  daggerok/oracle:11.2.0.2-xe
# daggerok/oracle:latest
# daggerok/oracle

Parameters:
  --name         The name of the container (default: auto generated)
  --shm-size     Amount of Linux shared memory
  -p             The port mapping of the host port to the container port.
                 Two ports are exposed: 1521 (Oracle Listener), 8080 (APEX)
  -e ORACLE_PWD  The Oracle Database SYS, SYSTEM and PDB_ADMIN password (default: auto generated)

  -v /u01/app/oracle/oradata

                 The data volume to use for the database.
                 Has to be writable by the Unix "oracle" (uid: 54321) user inside the container!
                 If omitted the database will not be persisted over container recreation.

  -v /u01/app/oracle/scripts/startup | /docker-entrypoint-initdb.d
  -v /u01/app/oracle/scripts/setup   | /docker-entrypoint-initdb.d

                 Optional: A volume with custom scripts to be run after database startup.
                 For further details see the "Running scripts after setup and on startup" section below.
----

.docker-compose usage (simple)
[sources,yaml]
----
version: "2.1"

services:
  oracle-xe:
    image: daggerok/oracle
    shm_size: 1g
    environment:
      ORACLE_PWD: password
    ports: ["1521:1521"]
    networks: [backing-services]
    healthcheck:
      test: curl -uSYSTEM:$$ORACLE_PWD -v http://127.0.0.1:8080//apex/
      interval: 15s
      timeout: 2s
      retries: 22

networks:
  backing-services:
    driver: bridge
----

.docker-compose usage (advanced)
[sources,yaml]
----
version: "2.1"

services:
  oracle-xe:
    image: daggerok/oracle:11.2.0.2-xe
    shm_size: 1g
    environment:
      ORACLE_PWD: password
    ports:
    - "1521:1521"
    - "8080:8080"
    volumes:
    - "oracle-xe-data:/u01/app/oracle/oradata"
    - "./db-startup-migration-scripts:/u01/app/oracle/scripts/startup"
    - "./db-setup-migration-scripts:/u01/app/oracle/scripts/setup
    networks: [backing-services]
    restart: unless-stopped

volumes:
  oracle-xe-data: {}

networks:
  backing-services:
    driver: bridge
----


.Running scripts after setup and on startup. Example mounts the local directory `./migrations` to `/opt/oracle/migration-scripts` which is then searched for custom startup scripts:
[sources,bash]
----
docker run --rm --name oracle-xe \
  -p 1521:1521 \
  -v $PWD/migrations:/opt/oracle/scripts/startup \
  -v /home/oracle/oradata:/opt/oracle/oradata \
  daggerok/oracle:11.2.0.2-xe
----

The docker images can be configured to run scripts after setup and on startup.
Currently sh and sql extensions are supported.
For post-setup scripts just mount the volume /opt/oracle/scripts/setup or extend the image to include scripts in this directory.
For post-startup scripts just mount the volume /opt/oracle/scripts/startup or extend the image to include scripts in this directory.
Both of those locations are also represented under the symbolic link /docker-entrypoint-initdb.d.
This is done to provide synergy with other database Docker images. The user is free to decide whether he wants to put his setup and startup scripts under /opt/oracle/scripts or /docker-entrypoint-initdb.d.

After the database is setup and/or started the scripts in those folders will be executed against the database in the container.
SQL scripts will be executed as sysdba, shell scripts will be executed as the current user.
To ensure proper order it is recommended to prefix your scripts with a number.
For example, in Flyway-style:

- V201711031__app_v1_initial_DDL.sql
- V201711032__app_v1_initial_DML.sql
- V201804021__app_v2_migration_scripts.sql
- ...

Note: The startup scripts will also be executed after the first time database setup is complete.

== sqlplus

.sqlplus Mac OS X installation
[sources,bash]
----
wget https://github.com/daggerok/oracle/releases/download/oracle/sqlplus-macos.x64-12.2.0.1.0-2.zip
unzip sqlplus-macos.x64-12.2.0.1.0-2.zip
export PATH=$PWD/sqlplus:$PATH
sqlplus -HV
----

.sqlplus connection and usage
[sources,bash]
----
# docker run ... -e ORACLE_PWD=password ... daggerok/oracle

sqlplus system/password@//0.0.0.0/XE

SQL*Plus: Release 12.2.0.1.0 Production on Tue Apr 24 21:38:50 2018

Copyright (c) 1982, 2017, Oracle.  All rights reserved.


Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> select * from dual;
SQL> ...
SQL> quit
Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
----

== apply sql migrations

_required running oracle in docker, sqlplus installed, bash / cygwin shell_

.try prepared sample with tablespace / user / DDL:
[sources,bash]
----
# run oracle for example with ORACLE_PWD: password
# docker run ... -e ORACLE_PWD=password ... daggerok/oracle

wget https://github.com/daggerok/oracle/releases/download/oracle/sqlplus-sample.zip
unzip -d /tmp sqlplus-sample.zip
bash /tmp/sqlplus-sample/sqlplus-cmd.bash
# verify that `my_app` username / password schema should contains groups and users tables...
----
