version: "2.1"

services:

  oracle-xe:
    image: daggerok/oracle:11.2.0.2-xe
    environment:
      ORACLE_PWD: password
    shm_size: 1g
    ports: ["1521:1521"]
    networks: [backing-services]

networks:
  backing-services:
    driver: bridge
